name: Go Test

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.go'
  push:
    branches:
      - main
    paths:
      - '**/*.go'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Run tests
        run: go test ./...
